services:
  - name: waf-app
    type: web
    runtime: docker
    repo: https://github.com/shyampillai07/WAF_Project
    branch: main
    plan: free
    envVars:
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        value: "sqlite:////opt/render/database/waf_logs.db"
    disk:
      name: waf-data
      mountPath: /opt/render/database
      sizeGB: 1
    healthCheckPath: "/"
    autoDeploy: true